schema_version = "1.0.0"

id = "readyplayerme_blender_importer"
version = "2.3.5"
name = "ReadyPlayerMe Blender Importer"
tagline = "Import ReadyPlayerMe avatars directly into Blender"
maintainer = "BeyondDev (Tyler Walker)"
type = "add-on"

tags = ["Animation", "Rigging"]

website = "https://github.com/tdw46/ReadyPlayerMe-Blender-Importer"

blender_version_min = "4.2.0"
blender_version_max = "4.5.999"

license = ["SPDX:GPL-3.0-or-later"]

copyright = [
  "Tyler Walker",
]

platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]

wheels = [
  "./wheels/pywebview-3.4-py3-none-any.whl",
  "./wheels/pythonnet-3.0.5-py3-none-any.whl",
  "./wheels/clr_loader-0.2.8-py3-none-any.whl",
  "./wheels/pycparser-2.23-py3-none-any.whl",
  "./wheels/cffi-2.0.0-cp311-cp311-win_amd64.whl",
  "./wheels/cffi-2.0.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/cffi-1.17.1-cp311-cp311-macosx_10_9_x86_64.whl",
  "./wheels/cffi-2.0.0b1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
]